### ISSUE TITLE
討論團隊的分工方式

### ISSUE THREAD

**Issue by wlabpmlee** [wlabpmlee/wlabpmlee-repo-1#1]
組長/PM (Project Manager)

- 建立與維護 Repository 及 Project
- 審查 (Review) 與批准 (Approve) 文件

組員/SA (System Analyst)

- 建立與維護文件
- 審查 (Review) 與批准 (Approve) 程式碼

組員/PG (Programmer)

- 建立與維護程式碼
- 建立 Pull Request

**Comment by wlabsalin** [comment]
贊成

**Comment by wlabpgliu** [comment]
贊成
